arrowParens: always
bracketSameLine: false
bracketSpacing: true
htmlWhitespaceSensitivity: css
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 100
proseWrap: preserve
requirePragma: false
quoteProps: as-needed
semi: false
singleQuote: true
trailingComma: all
tabWidth: 2
useTabs: false
